server:
  port: 8082

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##SURAJ
    password: Surexs2902@
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate: org.hibernate.dialect.Oracle8iDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8086
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka