
server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    password: SuraT9999
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   properties:
     hibernate:
       dialect:org.hibernate.dialect.MySQL57Dialect
   hibernate:
      ddl-auto: update
   show-sql: true

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8086

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-27241892.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client-credentials
            scope: internal
            client-id: 0oa99f46rpTIVU9Md5d7
            client-secret: GHyDl1eTyZS8QuZs18ZBWKpM7EPPORp-shhTpa5f
        provider:
          okta:
            issuer-uri: https://dev-27241892.okta.com/oauth2/default






#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 6s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-27241892.okta.com/oauth2/default
    audience: api://default




